# -*- coding: utf-8 -*-
"""Multimodal Retrival-Augmented Generation for  Factual Qestion answering with Cross Modal Hallcination Reduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsGeVPBEeXF2wcBdmka9wsKMLpnYGx1U
"""

!pip install wikipedia-api
!pip install sentence-transformers
!pip install faiss-cpu
!pip install transformers
!pip install torch

import wikipediaapi
import numpy as np
import faiss
import torch

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

wiki = wikipediaapi.Wikipedia(
    language='en',
    user_agent='HosainRAGProject/1.0'
)

topic = "Artificial intelligence"
page = wiki.page(topic)

text = page.text
print("Text length:", len(text))

def chunk_text(text, chunk_size=500, overlap=100):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start += chunk_size - overlap
    return chunks

chunks = chunk_text(text)
print("Total chunks:", len(chunks))

embed_model = SentenceTransformer('all-mpnet-base-v2')

embeddings = embed_model.encode(chunks)
embeddings = np.array(embeddings).astype('float32')

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print("FAISS index ready ")

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
llm_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_answer(query):
    context_chunks = retrieve(query)
    context = "\n\n".join(context_chunks)

    prompt = f"""
Answer the question ONLY using the context below.
If the answer is not found, say:
"Answer not found in provided Wikipedia data."

Context:
{context}

Question:
{query}
"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=200,
        temperature=0
    )

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return answer

while True:
    question = input("Ask a question: ")
    print(generate_answer(question))